server:
  port: 7002
spring:
  datasource:
#    driver-class-name: org.hsqldb.jdbcDriver
#    url:  jdbc:hsqldb:mem:mydatabase
#    username: sa
#    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.10/hops_pay?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.10.10:8761/eureka/     
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: ${spring.cloud.client.ip-address}
    