server:
  port: 7003
spring:
  application:
    name: hops-microservice-product
  data:
    mongodb:
      uri: mongodb://foxproduct:fox123456@192.168.10.10:27017/foxproduct?authMechanism=SCRAM-SHA-1
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.10:8761/eureka/
  instance:
    prefer-ip-address: true