server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
logging:
  levels:
    com.netflix.eureka: false
    com.netflix.discovery: false